Teststation/Controllers/CandidateManagementController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Teststation.Models;
using Teststation.Models.ViewModels;
using Microsoft.Office.Interop.Word;
using Microsoft.AspNetCore.Authorization;

namespace Teststation.Controllers
{
    [Authorize(Roles = Consts.Admin)]
    public class CandidateManagementController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signManager;
        private Database _context;
        public CandidateManagementController(Database context, UserManager<User> userManager, SignInManager<User> signManager)
        {
            _userManager = userManager;
            _signManager = signManager;
            _context = context;
        }
        public IActionResult CandidateList()
        {
            var candidates = _userManager.GetUsersInRoleAsync(Consts.Candidate).Result.Where(x=>!x.IsDeleted);

            var candidateList = new List<CandidateListEntryViewModel>();
            foreach (var candidate in candidates)
            {                
                candidateList.Add(new CandidateListEntryViewModel
                {
                    User = candidate,
                    UserId = candidate.Id,
                    Name = candidate.UserName,
                });
            }
            return View(candidateList);
        }

        public IActionResult CandidateDetails(string id)
        {
            if (!_context.Users.Any(x=>x.Id == id))
            {
                return RedirectToAction("CandidateList");
            }
            var viewModel = new CandidateSessionViewModel(_context, id);           
            return View(viewModel);
        }

        public async Task<IActionResult> DeleteCandidate(string id)
        {
            var user = _context.Users.FirstOrDefault(x => x.Id == id);
            user.UserName =
                user.NormalizedUserName =
                user.Email =
                user.NormalizedEmail =
                user.PasswordHash = null;
            user.IsDeleted = true;
            await _userManager.RemoveFromRolesAsync(user, new List<string>() { Consts.Admin, Consts.Candidate });
            _context.Users.Update(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(CandidateList));
        }

        public async Task<IActionResult> DeleteSession(long testId, string userId)
        {
            var user = _context.Users.FirstOrDefault(x => x.Id == userId);
            var session = _context.Sessions.FirstOrDefault(x => x.TestId == testId && x.CandidateId == user.Id);
            var mathAnswers = _context.MathAnswers.Where(x => x.CandidateId == user.Id && x.Question.TestId == testId);
            var multipleChoiceAnswers = _context.MultipleChoiceAnswers.Where(x => x.CandidateId == user.Id && x.Choice.Question.TestId == testId);
            var circuitAnswers = _context.CircuitAnswers.Where(x => x.CandidateId == user.Id && x.Resistor.CircuitPart.Question.TestId == testId);

            _context.MathAnswers.RemoveRange(mathAnswers);
            _context.MultipleChoiceAnswers.RemoveRange(multipleChoiceAnswers);
            _context.Sessions.Remove(session);
            _context.SaveChanges();
            return RedirectToAction("CandidateDetails", new { id = userId });
        }

        #region Word

        public IActionResult ExportResults(string id)
        {
            var userId = id;
            var viewModel = new CandidateSessionViewModel(_context, userId);

            object fileName = @"Beurteilung_Erprobung_"+ viewModel.User.UserName + ".docx";
            ApplicationClass app = new ApplicationClass();
            object missing = System.Reflection.Missing.Value;
            Document document = app.Application.Documents.Add();
            document.Paragraphs.Format.Alignment = WdParagraphAlignment.wdAlignParagraphJustify;

            document.Paragraphs.SpaceAfter = 0;
            document.Paragraphs.SpaceBefore = 0;
            document.Paragraphs.SpaceAfterAuto = 0;
            document.Paragraphs.SpaceBeforeAuto = 0;
            AddFootRow(document, missing, viewModel.User.UserName);
            AddDateToDocument(document, missing);
            AddHeadText(document, missing, viewModel.User.UserName);
            AddTable(document, missing, viewModel, app);
            AddTextAfterTable(document, missing);
            AddQualificationList(document, missing);
            AddNameOfAdmin(document, missing);
           

            document.SaveAs2(ref fileName,
                ref missing, ref missing, ref missing, ref missing, ref missing,
                ref missing, ref missing, ref missing, ref missing, ref missing,
                ref missing, ref missing, ref missing, ref missing, ref missing);
            document.Close();

            return RedirectToAction("CandidateDetails", new { id = userId });
        }


        private void AddDateToDocument(Document document, object missing)
        {            
            Paragraph paragraph = StyleForLargeText(document, missing);
            paragraph.Range.Text = "Erprobung am " + DateTime.Now.ToString("dd.MM.yyyy")+"\n";            
        }
        private void AddHeadText(Document document, object missing, string userName)
        {
            Paragraph paragraph = StyleForNormalText(document, missing);
            paragraph.Range.Text =
                "\n" +
                "Name des Teilnehmers: [Vorname] [Nachname]\n" +
                "\n" +
                "[Anrede] [Nachname] brachte zu Beginn der Erprobung zum Ausdruck, dass er sich für den Beruf des Fachinformatikers, Anwendungsentwicklung interessiert.\n" +
                "\n" +
                "Folgende Inhalte wurden getestet:\n" +
                "\n";      
        }
        private void AddTable(Document document, object missing, CandidateSessionViewModel viewModel, ApplicationClass app)
        {
            Paragraph paragraph = StyleForNormalText(document, missing);            
            var table = paragraph.Range.Tables.Add(paragraph.Range, viewModel.Tests.Count + 3, 6);
            table.Columns[1].Width = app.Application.CentimetersToPoints(8.11f);
            table.Columns[2].Width = app.Application.CentimetersToPoints(1.43f);
            table.Columns[3].Width = app.Application.CentimetersToPoints(1.43f);
            table.Columns[4].Width = app.Application.CentimetersToPoints(1.43f);
            table.Columns[5].Width = app.Application.CentimetersToPoints(1.79f);
            table.Columns[6].Width = app.Application.CentimetersToPoints(2.99f);

            TableHeader(table);
            SetTableStyle(table, app);            
            TableTests(table, viewModel);
            TableFooter(table, viewModel);            
        }
        private void TableHeader(Table table)
        {
            table.Cell(1, 1).Range.Text = "Aufgaben";
            table.Cell(1, 1).Range.Bold = 1;
            table.Cell(1, 1).Borders[WdBorderType.wdBorderBottom].LineStyle = WdLineStyle.wdLineStyleNone;
            table.Cell(2, 1).Borders[WdBorderType.wdBorderTop].LineStyle = WdLineStyle.wdLineStyleNone;

            table.Cell(1, 2).Range.Text = "Tag";
            table.Cell(1, 2).Range.Bold = 1;
            table.Cell(1, 3).Merge(table.Cell(1, 4));
            table.Cell(1, 2).Merge(table.Cell(1, 3));

            table.Cell(2, 2).Range.Text = "1";
            table.Cell(2, 3).Range.Text = "2";
            table.Cell(2, 4).Range.Text = "3";

            table.Cell(1, 3).Range.Text = "Ergebnis";
            table.Cell(1, 3).Range.Bold = 1;
            table.Cell(1, 3).Merge(table.Cell(1, 4));

            table.Cell(2, 5).Range.Text = "in %";
            table.Cell(2, 6).Range.Text = "Note IHK";
        }

        private void SetTableStyle(Table table, ApplicationClass app)
        {
            table.Range.Bold = 0;
            table.Range.Font.Size = 12;
            table.Spacing = 0;

            for (int r = 0; r <= table.Rows.Count; r++)
            {
                for (int c = 0; c <= table.Columns.Count; c++)
                {
                    try
                    {
                        table.Cell(r, c).Range.Borders[WdBorderType.wdBorderLeft].LineStyle = WdLineStyle.wdLineStyleSingle;
                        table.Cell(r, c).Range.Borders[WdBorderType.wdBorderRight].LineStyle = WdLineStyle.wdLineStyleSingle;
                        table.Cell(r, c).Range.Borders[WdBorderType.wdBorderTop].LineStyle = WdLineStyle.wdLineStyleSingle;
                        table.Cell(r, c).Range.Borders[WdBorderType.wdBorderBottom].LineStyle = WdLineStyle.wdLineStyleSingle;

                        table.Cell(r, c).HeightRule = WdRowHeightRule.wdRowHeightAuto;
                        table.Cell(r, c).Range.Paragraphs.SpaceAfter = 0;
                        table.Cell(r, c).Range.Paragraphs.SpaceBefore = 0;
                        table.Cell(r, c).Range.Italic = 1;
                        table.Cell(r, c).Range.Font.Name = "Frutiger 45 light";
                        table.Cell(r, c).Range.Font.Size = 12;
                    }
                    catch { }
                }
            }

            for (int r = 1; r <= 2; r++)
            {
                for (int c = 1; c <= 6; c++)
                {
                    try
                    {
                        table.Cell(r, c).Range.Shading.BackgroundPatternColor = WdColor.wdColorGray05;
                    }
                    catch { }
                }
            }

            for (int c = 1; c <= 6; c++)
            {
                try
                {
                    table.Cell(1, c).Range.ParagraphFormat.Alignment = WdParagraphAlignment.wdAlignParagraphLeft;
                    table.Cell(1, c).VerticalAlignment = WdCellVerticalAlignment.wdCellAlignVerticalCenter;

Teststation/ViewComponents/TestListViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Teststation.Models;

namespace Teststation.ViewComponents
{
    public class TestListViewComponent : ViewComponent
    {
        private SignInManager<User> _signManager;
        private UserManager<User> _userManager;
        private readonly Database _context;

        public TestListViewComponent(Database context, UserManager<User> userManager, SignInManager<User> signManager)
        {
            _userManager = userManager;
            _signManager = signManager;
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var viewModel = new CandidateSessionViewModel(_context, _userManager.GetUserId(UserClaimsPrincipal));
            return View(viewModel);
        }
    }
}

Teststation/Views/Shared/_FooterPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<footer class="border-top footer text-muted">
    @if (SignInManager.IsSignedIn(User))
    {
        <div class="container">
            &copy; 2019 - Teststation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <a style="float:right; color:white" asp-area="" asp-controller="Home" asp-action="EasterEggs">Easter Eggs</a>
        </div>
    }
    else
    {
        <div class="container">
            &copy; 2019 - Teststation
        </div>
    }
</footer>

Teststation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teststation</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/TestCreation.css" />
    <link rel="stylesheet" href="~/css/HomePage.css" />
    <link rel="stylesheet" href="~/css/Account.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="btn btn-lg" asp-controller="Home" asp-action="Index">
                    Teststation
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Abmelden</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TestCreation" asp-action="Create">Neuer Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TestCreation" asp-action="Index">Tests</a>
                        </li>
                        <li></li>
                        <ul class="navbar-nav">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
                                </li>
                                <li class="nav-item">
                                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                </li>
                            }
                        </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_FooterPartial" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/sideNav.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Teststation/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teststation</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/TestCreation.css" />
    <link rel="stylesheet" href="~/css/TestAnswer.css" />
    <link rel="stylesheet" href="~/css/Evaluation.css" />
    <link rel="stylesheet" href="~/css/sideNav.css" />
    <link rel="stylesheet" href="~/css/TestCreation.css" />
    <link rel="stylesheet" href="~/css/HomePage.css" />
    <link rel="stylesheet" href="~/css/Account.css" />
    <link rel="stylesheet" href="~/css/CircuitQuestion.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="btn btn-lg" asp-controller="Home" asp-action="Index">
                    Teststation
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ml-auto">
                            <a asp-action="Logout" asp-controller="Account" class="nav-link text-dark">Abmelden</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div id="mySidenav" class="sidenav adminMainSidenav">
        <a asp-action="Index" asp-controller="TestCreation">Tests</a>
        <a asp-action="CandidateList" asp-controller="CandidateManagement">Erproblinge</a>
    </div>
    <div class="sidenav" id="sideRemnant" onmouseover="toggleNav()">
        <div class="h-100 d-table">
            <a id="navArrow" class="d-table-cell align-middle">&#11166;</a>
        </div>
    </div>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_FooterPartial" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/sideNav.js" asp-append-version="true"></script>
    <script src="~/js/Confirmation.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Teststation/Views/Shared/_LayoutCandidate.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teststation</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/TestCreation.css" />
    <link rel="stylesheet" href="~/css/TestAnswer.css" />
    <link rel="stylesheet" href="~/css/Evaluation.css" />
    <link rel="stylesheet" href="~/css/sideNav.css" />
    <link rel="stylesheet" href="~/css/HomePage.css" />
    <link rel="stylesheet" href="~/css/CircuitQuestion.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="btn btn-lg" asp-controller="Home" asp-action="Index">
                    Teststation
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ml-auto">
                            <a asp-action="Logout" asp-controller="Account" class="nav-link text-dark">Abmelden</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div id="mySidenav" class="sidenav candidateSidenav">
        @await Component.InvokeAsync("TestList")

    </div>
    <div class="sidenav" id="sideRemnant" onmouseover="toggleNav()">
        <div class="h-100 d-table">
            <a id="navArrow" class="d-table-cell align-middle">&#11166;</a>
        </div>
    </div>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_FooterPartial" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/sideNav.js" asp-append-version="true"></script>
    <script src="~/js/Confirmation.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>